// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObligatorioProg3.Models;

#nullable disable

namespace ObligatorioProg3.Migrations
{
    [DbContext(typeof(ObligatorioP3Context))]
    partial class ObligatorioP3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioProg3.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("Id")
                        .HasName("PK__Clientes__3214EC27A8AADB0A");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Clima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripciónClima")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<short>("Temperatura")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Clima__3214EC27DE0A7907");

                    b.ToTable("Clima", (string)null);
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombrePlato")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int")
                        .HasColumnName("RestauranteID");

                    b.HasKey("Id")
                        .HasName("PK__Menu__3214EC277A9EBA02");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int")
                        .HasColumnName("RestauranteID");

                    b.HasKey("Id")
                        .HasName("PK__Mesas__3214EC27E8E94DAE");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.HasKey("Id")
                        .HasName("PK__OrdenDet__3214EC27C97BA4AB");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenDetalles");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Ordene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservaId")
                        .HasColumnType("int")
                        .HasColumnName("ReservaID");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Ordenes__3214EC276BDF29A0");

                    b.HasIndex("ReservaId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<int>("ClimaId")
                        .HasColumnType("int")
                        .HasColumnName("ClimaID");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Moneda")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int")
                        .HasColumnName("ReservaID");

                    b.Property<double>("TasaCambio")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Pagos__3214EC27BB1C6511");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClimaId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<string>("TipoPermisos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Permisos__3214EC2737D74335");

                    b.HasIndex("RolId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaReseña")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Puntaje")
                        .HasColumnType("tinyint");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int")
                        .HasColumnName("RestauranteID");

                    b.HasKey("Id")
                        .HasName("PK__Reseñas__3214EC27242CF2E5");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("Estado")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime");

                    b.Property<int>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("MesaID");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int")
                        .HasColumnName("RestauranteID");

                    b.HasKey("Id")
                        .HasName("PK__Reservas__3214EC2722C5E044");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Restaura__3214EC278ED62150");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC277562E1B3");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC273E215491");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Cliente", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Clientes__Usuari__3D5E1FD2");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Menu", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Restaurante", "Restaurante")
                        .WithMany("Menus")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("FK__Menu__Restaurant__4BAC3F29");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Mesa", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("FK__Mesas__Restauran__4316F928");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.OrdenDetalle", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Menu", "Menu")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("MenuId")
                        .IsRequired()
                        .HasConstraintName("FK__OrdenDeta__MenuI__52593CB8");

                    b.HasOne("ObligatorioProg3.Models.Ordene", "Orden")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK__OrdenDeta__Orden__5165187F");

                    b.Navigation("Menu");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Ordene", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Reserva", "Reserva")
                        .WithMany("Ordenes")
                        .HasForeignKey("ReservaId")
                        .IsRequired()
                        .HasConstraintName("FK__Ordenes__Reserva__4E88ABD4");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Pago", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__ClienteID__5AEE82B9");

                    b.HasOne("ObligatorioProg3.Models.Clima", "Clima")
                        .WithMany("Pagos")
                        .HasForeignKey("ClimaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__ClimaID__59FA5E80");

                    b.HasOne("ObligatorioProg3.Models.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__ReservaID__59063A47");

                    b.Navigation("Cliente");

                    b.Navigation("Clima");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Permiso", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Role", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Permisos__RolID__619B8048");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Resena", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Cliente", "Cliente")
                        .WithMany("Resenas")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Reseñas__Cliente__5DCAEF64");

                    b.HasOne("ObligatorioProg3.Models.Restaurante", "Restaurante")
                        .WithMany("Resenas")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("FK__Reseñas__Restaur__5EBF139D");

                    b.Navigation("Cliente");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Reserva", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__Client__46E78A0C");

                    b.HasOne("ObligatorioProg3.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__MesaID__47DBAE45");

                    b.HasOne("ObligatorioProg3.Models.Restaurante", "Restaurante")
                        .WithMany("Reservas")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__Restau__48CFD27E");

                    b.Navigation("Cliente");

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Usuario", b =>
                {
                    b.HasOne("ObligatorioProg3.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__RolID__398D8EEE");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Clima", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Menu", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Ordene", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Reserva", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Restaurante", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Mesas");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Role", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ObligatorioProg3.Models.Usuario", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
